### ISSUE TITLE
Loading of image channels from hdf5?

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-plateViewer#13]
Are the image channels (= separate datasets) from hdf5 loaded on demanded?
I think if `visible=False` in the attributes, the channel should not be loaded by default, it should only
be loaded when the user activates it.

Background: for the current project, I think we will end up with 15 or more channels per image.
To keep it less crowded, I will set `visible` to `False` for everything except the raw data.
If all these extra channels are then also loaded on demand, it would make the viewer more smooth.

**Comment by tischi** [comment]
I tested it and for the very first image it loads all of them even if they are rendered invisible, but I think waiting a bit longer for the very first image is acceptable. However once you start moving around it will only load the ones that are visible. So it should already be smooth as it is.

**Comment by constantinpape** [comment]
> but I think waiting a bit longer for the very first image is acceptable

Yes, that's fine.

> However once you start moving around it will only load the ones that are visible. So it should already be smooth as it is.

Ok, sounds good.
